"""
brief_and_tweet.py
Reads the last 24h of floods.csv, generates a 3-sentence situation report
via Ollama Cloud, commits it as data/daily_brief.md, and posts to Twitter/X.

Run after main.py in the nightly GitHub Actions workflow.
Place this file at src/brief_and_tweet.py in the repo.
"""

import csv
import os
import re
import sys
import textwrap
from datetime import datetime, timezone, timedelta
from pathlib import Path

import requests


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

OLLAMA_API_KEY        = os.environ["OLLAMA_API_KEY"]
TWITTER_API_KEY       = os.environ["TWITTER_API_KEY"]
TWITTER_API_SECRET    = os.environ["TWITTER_API_SECRET"]
TWITTER_ACCESS_TOKEN  = os.environ["TWITTER_ACCESS_TOKEN"]
TWITTER_ACCESS_SECRET = os.environ["TWITTER_ACCESS_SECRET"]

# Resolve paths relative to this file so it works locally and in Actions
SRC_DIR    = Path(__file__).parent
REPO_ROOT  = SRC_DIR.parent
DATA_DIR   = REPO_ROOT / "data"
CSV_PATH   = DATA_DIR / "floods.csv"
BRIEF_PATH = DATA_DIR / "daily_brief.md"

OLLAMA_MODEL    = "gpt-oss:120b"
OLLAMA_BASE_URL = "https://api.ollama.com/api/chat"
LOOKBACK_HOURS  = 24
MAX_TWEET_CHARS = 280


# ---------------------------------------------------------------------------
# Step 1 — load recent events from CSV
# ---------------------------------------------------------------------------

def load_recent_events(hours: int = LOOKBACK_HOURS) -> list[dict]:
    cutoff = datetime.now(timezone.utc) - timedelta(hours=hours)
    events = []
    if not CSV_PATH.exists():
        print(f"[brief] CSV not found at {CSV_PATH}, skipping.")
        return events
    with open(CSV_PATH, newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            try:
                raw = row.get("published_at") or row.get("run_at") or ""
                pub = datetime.fromisoformat(raw.replace("Z", "+00:00"))
            except (KeyError, ValueError):
                continue
            if pub >= cutoff:
                events.append(row)
    return events


def summarise_events(events: list[dict]) -> str:
    if not events:
        return "No flood events detected in the last 24 hours."
    lines = []
    for e in events:
        lines.append(
            f"- [{e.get('flood_type', 'unknown')}] {e.get('title', '')} "
            f"| {e.get('osm_display', '')} | {e.get('published_at', '')}"
        )
    return "\n".join(lines[:60])   # cap at 60 rows to keep prompt small


# ---------------------------------------------------------------------------
# Step 2 — call Ollama Cloud
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = textwrap.dedent("""
    You are a concise, factual flood-news analyst writing for a public
    situational-awareness feed. Respond with exactly 3 sentences:
      1. Overall activity level and primary geography affected.
      2. The single most notable event or cluster.
      3. Any dominant flood-type pattern or emerging trend.
    Do not use bullet points. Do not include hashtags. Plain prose only.
""").strip()


def generate_brief(event_summary: str) -> str:
    today = datetime.now(timezone.utc).strftime("%B %d, %Y")
    user_msg = (
        f"Today is {today}. Here are US flood news events from the last 24 hours:\n\n"
        f"{event_summary}\n\n"
        "Write the 3-sentence situation report now."
    )
    payload = {
        "model": OLLAMA_MODEL,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": user_msg},
        ],
        "stream": False,
    }
    headers = {
        "Authorization": f"Bearer {OLLAMA_API_KEY}",
        "Content-Type": "application/json",
    }
    resp = requests.post(OLLAMA_BASE_URL, json=payload, headers=headers, timeout=60)
    resp.raise_for_status()
    return resp.json()["message"]["content"].strip()


# ---------------------------------------------------------------------------
# Step 3 — write data/daily_brief.md
# ---------------------------------------------------------------------------

def write_brief(brief_text: str, event_count: int) -> None:
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    md = textwrap.dedent(f"""
        # US Flood Situation Report — {today}

        *Generated by [floodwire2](https://github.com/rmkenv/floodwire2) · {event_count} events in last 24h*

        {brief_text}

        ---
        *Auto-generated via Ollama Cloud ({OLLAMA_MODEL}). Not a forecast.*
        *Source: SerpAPI Google News + OSM Nominatim.*
    """).strip() + "\n"
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    BRIEF_PATH.write_text(md, encoding="utf-8")
    print(f"[brief] Wrote {BRIEF_PATH}")


# ---------------------------------------------------------------------------
# Step 4 — OAuth 1.0a Twitter/X post (stdlib only, no tweepy needed)
# ---------------------------------------------------------------------------

def _oauth1_header(method: str, url: str, params: dict) -> str:
    import base64
    import hashlib
    import hmac
    import time
    import urllib.parse
    import uuid

    nonce     = uuid.uuid4().hex
    timestamp = str(int(time.time()))

    oauth_params = {
        "oauth_consumer_key":     TWITTER_API_KEY,
        "oauth_nonce":            nonce,
        "oauth_signature_method": "HMAC-SHA1",
        "oauth_timestamp":        timestamp,
        "oauth_token":            TWITTER_ACCESS_TOKEN,
        "oauth_version":          "1.0",
    }

    all_params  = {**params, **oauth_params}
    sorted_str  = "&".join(
        f"{urllib.parse.quote(k, safe='')}={urllib.parse.quote(str(v), safe='')}"
        for k, v in sorted(all_params.items())
    )
    base_string = "&".join([
        method.upper(),
        urllib.parse.quote(url, safe=""),
        urllib.parse.quote(sorted_str, safe=""),
    ])
    signing_key = (
        urllib.parse.quote(TWITTER_API_SECRET, safe="")
        + "&"
        + urllib.parse.quote(TWITTER_ACCESS_SECRET, safe="")
    )
    signature = base64.b64encode(
        hmac.new(signing_key.encode(), base_string.encode(), hashlib.sha1).digest()
    ).decode()

    oauth_params["oauth_signature"] = signature
    header_parts = ", ".join(
        f'{urllib.parse.quote(k, safe="")}="{urllib.parse.quote(str(v), safe="")}"'
        for k, v in sorted(oauth_params.items())
    )
    return f"OAuth {header_parts}"


def build_tweet(brief_text: str, event_count: int) -> str:
    today    = datetime.now(timezone.utc).strftime("%b %d")
    hashtags = "#flooding #weather #USGS"
    header   = f"🌊 US Flood Brief — {today} ({event_count} events)\n\n"
    footer   = f"\n\n{hashtags}"
    budget   = MAX_TWEET_CHARS - len(header) - len(footer)

    sentences = re.split(r'(?<=\.)\s+', brief_text)
    body = ""
    for s in sentences:
        candidate = (body + " " + s).strip()
        if len(candidate) <= budget:
            body = candidate
        else:
            break
    if not body:
        body = brief_text[:budget].rstrip() + "…"

    return header + body + footer


def post_tweet(text: str) -> dict:
    url  = "https://api.twitter.com/2/tweets"
    auth = _oauth1_header("POST", url, {})
    resp = requests.post(
        url,
        json={"text": text},
        headers={"Authorization": auth, "Content-Type": "application/json"},
        timeout=30,
    )
    resp.raise_for_status()
    return resp.json()


# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------

def main() -> None:
    print("[brief] Loading recent events …")
    events = load_recent_events()
    print(f"[brief] {len(events)} events in last {LOOKBACK_HOURS}h")

    summary = summarise_events(events)

    print("[brief] Generating situation report via Ollama …")
    brief = generate_brief(summary)
    print(f"[brief] Brief:\n{brief}\n")

    write_brief(brief, len(events))

    tweet_text = build_tweet(brief, len(events))
    print(f"[brief] Tweet ({len(tweet_text)} chars):\n{tweet_text}\n")

    print("[brief] Posting to Twitter/X …")
    result   = post_tweet(tweet_text)
    tweet_id = result.get("data", {}).get("id", "unknown")
    print(f"[brief] Posted — tweet id {tweet_id}")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"[brief] ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
